language: elixir
elixir:
  - 1.5.1
otp_release:
  - 20.0

before_install:
  - mix do local.hex --force, local.rebar --force
  - MIX_ENV=test mix deps.get
script:
  - "MIX_ENV=test mix coveralls.travis"

notifications:
  slack:
    secure: EvBURke07MNjt00wmXOfeoUdlzy4XgXMxtKx9ZcgGT+ob+gxXEvm9Ayayz9LHET0WWwYoe4XhRLvFNNfNxvtdvKfo/AukjFIjr8gbqIcAoeRiY8V1STnwFjej2UbkFI1OmvxXG5ttWikAL9kLxTcTXcrSRbMfthaIfDPKrLvXdmMaEv5YtVwyHwHi8QlQKZ+huUOquxFf3G7mnf/LWhuZMB1LPzDhjeXnRCLND+LZKxEK9jHiD6xm5560jyK2PM4vFICmzvTzg4FQhz1Zua0AeXJIR1CUp3KBwhkIWn5ujzB1huDKiiXVctXRPD7Rd8JypoMqhELn0l3OkHKGBQRCyG2l1iPW9vzwhXOfL+0hRcltJhI+HgbPs3+JkYnYF9UN84um6Dp28Ma1dm8+RBPIsOtcKubrnhJK9F+u7ZOcbtFCk0fE3U7KzdnsN35dQjdA1fa/3JiFdt6sZ4jYbNKpW34LGMPpwdWCD9AT2zXORFD+WPeoF8QzE5dheAR16h7QevwTLEsbMhMN/PXJAt724kw1Ev+7MRMHT7J2XL3m7NAk+qTb+yYnRjkT5qgXnJqZ6y5DyBUXYAjOUuGNnRE29ZGETolh119X6njpJNi8VziyQIXopnglAbGHQIRRovOYwpiqh0hGVWcj0EDO+mXsxHJYMvpkbGI5nnTzH2uiFM=
